"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WriteStorage__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var WriteStorage__factory_1 = require("./WriteStorage__factory");
Object.defineProperty(exports, "WriteStorage__factory", { enumerable: true, get: function () { return WriteStorage__factory_1.WriteStorage__factory; } });
