/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TheHydraRender } from "./TheHydraRender";
export type { TheHydraRenderer } from "./TheHydraRenderer";
