/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TheHydraRenderInterface extends utils.Interface {
  functions: {
    "dataStore()": FunctionFragment;
    "drawSVGToBytes(bytes)": FunctionFragment;
    "drawSVGToString(bytes)": FunctionFragment;
    "getOnChainPhotoSVG(uint256)": FunctionFragment;
    "getOnChainPhotoSVGAsBase64(uint256)": FunctionFragment;
    "theHydra()": FunctionFragment;
    "tokenURI(uint256,string)": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "xqstgfx()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "dataStore"
      | "drawSVGToBytes"
      | "drawSVGToString"
      | "getOnChainPhotoSVG"
      | "getOnChainPhotoSVGAsBase64"
      | "theHydra"
      | "tokenURI(uint256,string)"
      | "tokenURI(uint256)"
      | "xqstgfx"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "dataStore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "drawSVGToBytes",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "drawSVGToString",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getOnChainPhotoSVG",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getOnChainPhotoSVGAsBase64",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "theHydra", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI(uint256,string)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "xqstgfx", values?: undefined): string;

  decodeFunctionResult(functionFragment: "dataStore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drawSVGToBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "drawSVGToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOnChainPhotoSVG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOnChainPhotoSVGAsBase64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "theHydra", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenURI(uint256,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenURI(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xqstgfx", data: BytesLike): Result;

  events: {};
}

export interface TheHydraRender extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TheHydraRenderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    dataStore(overrides?: CallOverrides): Promise<[string]>;

    drawSVGToBytes(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    drawSVGToString(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getOnChainPhotoSVG(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getOnChainPhotoSVGAsBase64(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    theHydra(overrides?: CallOverrides): Promise<[string]>;

    "tokenURI(uint256,string)"(
      id: PromiseOrValue<BigNumberish>,
      renderType: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "tokenURI(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    xqstgfx(overrides?: CallOverrides): Promise<[string]>;
  };

  dataStore(overrides?: CallOverrides): Promise<string>;

  drawSVGToBytes(
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  drawSVGToString(
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getOnChainPhotoSVG(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getOnChainPhotoSVGAsBase64(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  theHydra(overrides?: CallOverrides): Promise<string>;

  "tokenURI(uint256,string)"(
    id: PromiseOrValue<BigNumberish>,
    renderType: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  "tokenURI(uint256)"(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  xqstgfx(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    dataStore(overrides?: CallOverrides): Promise<string>;

    drawSVGToBytes(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    drawSVGToString(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getOnChainPhotoSVG(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getOnChainPhotoSVGAsBase64(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    theHydra(overrides?: CallOverrides): Promise<string>;

    "tokenURI(uint256,string)"(
      id: PromiseOrValue<BigNumberish>,
      renderType: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    "tokenURI(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    xqstgfx(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    dataStore(overrides?: CallOverrides): Promise<BigNumber>;

    drawSVGToBytes(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    drawSVGToString(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOnChainPhotoSVG(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOnChainPhotoSVGAsBase64(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    theHydra(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenURI(uint256,string)"(
      id: PromiseOrValue<BigNumberish>,
      renderType: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenURI(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    xqstgfx(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    dataStore(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    drawSVGToBytes(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    drawSVGToString(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOnChainPhotoSVG(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOnChainPhotoSVGAsBase64(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    theHydra(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenURI(uint256,string)"(
      id: PromiseOrValue<BigNumberish>,
      renderType: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenURI(uint256)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    xqstgfx(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
