"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TheHydraRenderer__factory = exports.TheHydraDataStore__factory = exports.TheHydra__factory = exports.Owned__factory = exports.ITheHydraRenderer__factory = exports.ITheHydraDataStore__factory = exports.ITheHydra__factory = exports.IExquisiteGraphics__factory = exports.ERC20__factory = exports.exquisiteGraphicsMockSol = exports.erc721Sol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.erc721Sol = __importStar(require("./ERC721.sol"));
exports.exquisiteGraphicsMockSol = __importStar(require("./ExquisiteGraphics.mock.sol"));
var ERC20__factory_1 = require("./ERC20__factory");
Object.defineProperty(exports, "ERC20__factory", { enumerable: true, get: function () { return ERC20__factory_1.ERC20__factory; } });
var IExquisiteGraphics__factory_1 = require("./IExquisiteGraphics__factory");
Object.defineProperty(exports, "IExquisiteGraphics__factory", { enumerable: true, get: function () { return IExquisiteGraphics__factory_1.IExquisiteGraphics__factory; } });
var ITheHydra__factory_1 = require("./ITheHydra__factory");
Object.defineProperty(exports, "ITheHydra__factory", { enumerable: true, get: function () { return ITheHydra__factory_1.ITheHydra__factory; } });
var ITheHydraDataStore__factory_1 = require("./ITheHydraDataStore__factory");
Object.defineProperty(exports, "ITheHydraDataStore__factory", { enumerable: true, get: function () { return ITheHydraDataStore__factory_1.ITheHydraDataStore__factory; } });
var ITheHydraRenderer__factory_1 = require("./ITheHydraRenderer__factory");
Object.defineProperty(exports, "ITheHydraRenderer__factory", { enumerable: true, get: function () { return ITheHydraRenderer__factory_1.ITheHydraRenderer__factory; } });
var Owned__factory_1 = require("./Owned__factory");
Object.defineProperty(exports, "Owned__factory", { enumerable: true, get: function () { return Owned__factory_1.Owned__factory; } });
var TheHydra__factory_1 = require("./TheHydra__factory");
Object.defineProperty(exports, "TheHydra__factory", { enumerable: true, get: function () { return TheHydra__factory_1.TheHydra__factory; } });
var TheHydraDataStore__factory_1 = require("./TheHydraDataStore__factory");
Object.defineProperty(exports, "TheHydraDataStore__factory", { enumerable: true, get: function () { return TheHydraDataStore__factory_1.TheHydraDataStore__factory; } });
var TheHydraRenderer__factory_1 = require("./TheHydraRenderer__factory");
Object.defineProperty(exports, "TheHydraRenderer__factory", { enumerable: true, get: function () { return TheHydraRenderer__factory_1.TheHydraRenderer__factory; } });
