/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITheHydraRenderer,
  ITheHydraRendererInterface,
} from "../ITheHydraRenderer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "getOnChainSVG",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "getOnChainSVG_AsBase64",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITheHydraRenderer__factory {
  static readonly abi = _abi;
  static createInterface(): ITheHydraRendererInterface {
    return new utils.Interface(_abi) as ITheHydraRendererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITheHydraRenderer {
    return new Contract(address, _abi, signerOrProvider) as ITheHydraRenderer;
  }
}
