"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITheHydra__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_originalId",
                type: "uint256",
            },
        ],
        name: "editionsGetInfoFromOriginal",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint256",
                        name: "originalId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "startId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "endId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "minted",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "gifted",
                        type: "uint256",
                    },
                    {
                        internalType: "bool",
                        name: "soldOut",
                        type: "bool",
                    },
                    {
                        internalType: "uint256",
                        name: "nextId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "localIndex",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "maxPerOriginal",
                        type: "uint256",
                    },
                ],
                internalType: "struct ITheHydra.EditionInfo",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class ITheHydra__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ITheHydra__factory = ITheHydra__factory;
ITheHydra__factory.abi = _abi;
