/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITheHydraDataStore,
  ITheHydraDataStoreInterface,
} from "../ITheHydraDataStore";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_originalId",
        type: "uint256",
      },
    ],
    name: "getData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOffChainBaseURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_baseURI",
        type: "string",
      },
    ],
    name: "setOffChainBaseURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_originalId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "storeData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITheHydraDataStore__factory {
  static readonly abi = _abi;
  static createInterface(): ITheHydraDataStoreInterface {
    return new utils.Interface(_abi) as ITheHydraDataStoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITheHydraDataStore {
    return new Contract(address, _abi, signerOrProvider) as ITheHydraDataStore;
  }
}
