/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace ITheHydra {
  export type EditionInfoStruct = {
    originalId: PromiseOrValue<BigNumberish>;
    startId: PromiseOrValue<BigNumberish>;
    endId: PromiseOrValue<BigNumberish>;
    minted: PromiseOrValue<BigNumberish>;
    gifted: PromiseOrValue<BigNumberish>;
    soldOut: PromiseOrValue<boolean>;
    nextId: PromiseOrValue<BigNumberish>;
    localIndex: PromiseOrValue<BigNumberish>;
    maxPerOriginal: PromiseOrValue<BigNumberish>;
  };

  export type EditionInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    originalId: BigNumber;
    startId: BigNumber;
    endId: BigNumber;
    minted: BigNumber;
    gifted: BigNumber;
    soldOut: boolean;
    nextId: BigNumber;
    localIndex: BigNumber;
    maxPerOriginal: BigNumber;
  };
}

export interface ITheHydraInterface extends utils.Interface {
  functions: {
    "editionsGetInfoFromOriginal(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "editionsGetInfoFromOriginal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "editionsGetInfoFromOriginal",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "editionsGetInfoFromOriginal",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITheHydra extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITheHydraInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    editionsGetInfoFromOriginal(
      _originalId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ITheHydra.EditionInfoStructOutput]>;
  };

  editionsGetInfoFromOriginal(
    _originalId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ITheHydra.EditionInfoStructOutput>;

  callStatic: {
    editionsGetInfoFromOriginal(
      _originalId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ITheHydra.EditionInfoStructOutput>;
  };

  filters: {};

  estimateGas: {
    editionsGetInfoFromOriginal(
      _originalId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    editionsGetInfoFromOriginal(
      _originalId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
