/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ITheHydraInterface extends utils.Interface {
  functions: {
    "getMaxEditionsPerOriginal()": FunctionFragment;
    "getOrigialTotalSupply()": FunctionFragment;
    "getOriginalId(uint256)": FunctionFragment;
    "getTotalSupply()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getMaxEditionsPerOriginal"
      | "getOrigialTotalSupply"
      | "getOriginalId"
      | "getTotalSupply"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMaxEditionsPerOriginal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrigialTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOriginalId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupply",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getMaxEditionsPerOriginal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrigialTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOriginalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupply",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITheHydra extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITheHydraInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getMaxEditionsPerOriginal(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOrigialTotalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOriginalId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTotalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getMaxEditionsPerOriginal(overrides?: CallOverrides): Promise<BigNumber>;

  getOrigialTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  getOriginalId(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getMaxEditionsPerOriginal(overrides?: CallOverrides): Promise<BigNumber>;

    getOrigialTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getOriginalId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getMaxEditionsPerOriginal(overrides?: CallOverrides): Promise<BigNumber>;

    getOrigialTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getOriginalId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getMaxEditionsPerOriginal(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrigialTotalSupply(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOriginalId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
