"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExquisiteGraphics__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ExquisiteGraphics__factory_1 = require("./ExquisiteGraphics__factory");
Object.defineProperty(exports, "ExquisiteGraphics__factory", { enumerable: true, get: function () { return ExquisiteGraphics__factory_1.ExquisiteGraphics__factory; } });
