"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TheHydraRenderer__factory = exports.TheHydraRender__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var TheHydraRender__factory_1 = require("./TheHydraRender__factory");
Object.defineProperty(exports, "TheHydraRender__factory", { enumerable: true, get: function () { return TheHydraRender__factory_1.TheHydraRender__factory; } });
var TheHydraRenderer__factory_1 = require("./TheHydraRenderer__factory");
Object.defineProperty(exports, "TheHydraRenderer__factory", { enumerable: true, get: function () { return TheHydraRenderer__factory_1.TheHydraRenderer__factory; } });
